// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef copack_h
#define copack_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Hold_Browser.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Browser.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Check_Button.H>

class Packer {
public:
  Packer();
  Fl_Window *main_window;
  Fl_Input_Choice *root_path;
  Fl_Button *select_path;
  Fl_Check_Browser *entry_apps;
  Fl_Check_Browser *plugin_apps;
  Fl_Choice *launch_choice;
  Fl_Input *add_pluginapp_text;
  Fl_Button *add_pluginapp_button;
  Fl_Text_Editor *param_editor;
  Fl_Hold_Browser *plugin_list;
private:
  void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
public:
  Fl_Return_Button *ok_button;
  Fl_Check_Button *is_cover_src;
  Fl_Check_Button *is_backup_src;
  Fl_Check_Button *is_retore_last;
  ~Packer();
};
#endif
